// Code generated by https://gotool.top
package dao

const TableNameMemo = "memo"

// Memo
type Memo struct {
	ID        uint64 `gorm:"primaryKey;autoIncrement" json:"id"`
	UID       string `gorm:"type:text;not null;uniqueIndex" json:"uid"`
	CreatorID uint64 `gorm:"not null;index" json:"creator_id"`

	CreatedTs int64 `gorm:"not null;autoCreateTime:nano" json:"created_ts"`
	UpdatedTs int64 `gorm:"not null;autoUpdateTime:nano" json:"updated_ts"`

	RowStatus string `gorm:"type:text;not null;default:'NORMAL'" json:"row_status"`
	Content   string `gorm:"type:text;not null;default:''" json:"content"`

	Visibility string `gorm:"type:text;not null;default:'PRIVATE'" json:"visibility"`
	Pinned     bool   `gorm:"not null;default:false" json:"pinned"`

	Payload string `gorm:"type:text;not null;default:'{}'" json:"payload"`
}

func (r *Memo) TableName() string {
	return TableNameMemo
}
